collection_name: agent
persist_directory: AgentProject\data\chroma
k: 3
data_path: AgentProject\data
md5_hex_store: AgentProject\data/md5.txt
allowed_knowledge_file_types:
  - .txt
  - .pdf
chunk_size: 200
chunk_overlap: 20
separators:
  - "\n\n"
  - "\n"
  - "。"
  - "！"
  - "？"
  - ","
  - ":"
  - ";"
  - "|"
  - " "